FROM centos:centos6
ENV LUMBERJACK_VERSION 0.4.0
ENV LUMBERJACK_BUILD_VERSION 1
ENV PATH /go/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin

RUN yum list \
        && yum groupinstall -yqq "Development Tools"

RUN yum list \
        && yum install -yqq wget unzip git tar libyaml libyaml-devel zlib zlib-devel openssl openssl-devel

#RUN yum list \
#        && yum install -yqq ruby ruby-devel rubygems

# ruby install:
ENV RUBY_MAJOR 1.9
ENV RUBY_VERSION 1.9.3-p550

RUN yum -y update && yum -y install ruby && yum clean all \
    && mkdir -p /usr/src/ruby \
    && curl -SL "http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.bz2" | tar -xjC /usr/src/ruby --strip-components=1 \
    && cd /usr/src/ruby \
    && autoconf \
    && ./configure --disable-install-doc \
    && make \
    && yum remove -y ruby \
    && make install \
    && rm -r /usr/src/ruby

ENV GEM_HOME /usr/local/bundle
ENV PATH $GEM_HOME/bin:$PATH
RUN gem install bundler \
    && bundle config --global path "$GEM_HOME" \
    && bundle config --global bin "$GEM_HOME/bin"

RUN git clone https://go.googlesource.com/go && cd go && git checkout go1.4.1 && cd src && GOROOT=/usr/local ./all.bash

RUN mkdir -p /app \
	&& mkdir -p /app/src \
	&& mkdir -p /app/bin \
	&& wget -O/app/src/logstash-forwarder-${LUMBERJACK_VERSION}.zip https://github.com/elasticsearch/logstash-forwarder/archive/v${LUMBERJACK_VERSION}.zip \
	&& echo ${LUMBERJACK_VERSION} > /app/lumberjack-version.txt	

RUN gem install bundler

WORKDIR /app/src
RUN unzip logstash-forwarder-${LUMBERJACK_VERSION}.zip
WORKDIR logstash-forwarder-${LUMBERJACK_VERSION}
RUN bundle --binstubs
RUN PATH=$GOPATH/bin:$PATH
RUN bundle exec make
RUN bundle exec make rpm

CMD cp /app/src/logstash-forwarder-${LUMBERJACK_VERSION}/logstash-forwarder-${LUMBERJACK_VERSION}-${LUMBERJACK_BUILD_VERSION}.x86_64.rpm /pkg

